after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
before_install:
  - "curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2"
  - "export PATH=\"$HOME/.yarn/bin:$PATH\""
before_script:
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"
install:
  - yarn
  - "yarn bootstrap"
language: node_js
node_js:
  - "8"
script: "yarn lint && yarn test --ci"
